In [2]:
import pandas as pd
import numpy as np

In [21]:
adsc_df = pd.read_csv('adsc_data2.csv', low_memory=False)

# Drop rows that has NaN values on selected columns
adsc_df=adsc_df.dropna(subset=['dod_id','as_of_date'])
adsc_df.to_csv('adsc_clean.csv',mode='w',index=False)

adsc_df = pd.read_csv('adsc_clean.csv', low_memory=False)

In [53]:
#adsc_df.info()
Dup_Rows = adsc_df[adsc_df.duplicated()]
print("\n\nDuplicate Rows : \n {}".format(Dup_Rows))
DF_RM_DUP = adsc_df.drop_duplicates(subset=['dod_id'],keep = 'last')
print('\n\nResult DataFrame after duplicate removal :\n', DF_RM_DUP.head(5))
DF_RM_DUP.to_csv('cleandata.csv',mode='w',index=False)

adsc_df = pd.read_csv('adsc_clean.csv', low_memory=False,dtype={'dod_id': str,'adsc1': float,'adsc2':float,'adsc3':float,'adsc4':float
,'adsc5':float,'adsc6':float})

adsc_df[['dt_adsc1','dt_adsc2','dt_adsc3','dt_adsc4']] = adsc_df[['dt_adsc1','dt_adsc2','dt_adsc3','dt_adsc4']].apply(pd.to_datetime, format='%y%m%d')

Duplicate Rows :
 Empty DataFrame
Columns: [dod_id, as_of_date, dt_adsc1, dt_adsc2, dt_adsc3, dt_adsc4, dt_adsc5, dt_adsc6, adsc1, adsc2, adsc3, adsc4, adsc5, adsc6]
Index: []


Result DataFrame after duplicate removal :
          dod_id as_of_date    dt_adsc1    dt_adsc2    dt_adsc3    dt_adsc4  \
80   9322867510  31MAY2014  20130805.0  20100625.0  20100430.0  20090801.0
99   9792632907  31MAY2014  20141004.0  20141004.0  20140720.0  20110611.0
103  8822330591  31MAY2014  20130708.0  20111203.0  20110901.0  20100713.0
136  1540512164  31MAY2014  20150929.0  20130602.0  20120903.0  20120831.0
152  6908880185  31MAY2014  20140926.0  20120729.0  20120729.0  20120728.0

       dt_adsc5    dt_adsc6  adsc1  adsc2  adsc3  adsc4  adsc5  adsc6
80   20051126.0         NaN   11.0   70.0    7.0   85.0    5.0    NaN
99   20110611.0  20090801.0   11.0   11.0   70.0   78.0    7.0   85.0
103  20100713.0  20100713.0   85.0   70.0    5.0   11.0   11.0   11.0
136  20110320.0  20100922.0   85.0    9.0   11.0   11.0   11.0   70.0
152  20120430.0  20090801.0   70.0   11.0   78.0   11.0    7.0   85.0

ValueError: unconverted data remains: 430

In [45]:
adsc_df.dtypes
adsc_df.head()

,dod_id,as_of_date,dt_adsc1,dt_adsc2,dt_adsc3,dt_adsc4,dt_adsc5,dt_adsc6,adsc1,adsc2,adsc3,adsc4,adsc5,adsc6
0,4828443528,31MAY2014,20130430.0,20120612.0,20120612.0,20100813.0,20100509.0,20050620.0,7.0,11.0,11.0,85.0,70.0,78.0
1,6790198895,31MAY2014,20160612.0,20160328.0,20111213.0,20111212.0,20090801.0,20090124.0,11.0,78.0,11.0,11.0,85.0,11.0
2,2463616604,31MAY2014,20150405.0,20110917.0,20101201.0,20100227.0,20100227.0,20100227.0,85.0,70.0,5.0,11.0,11.0,11.0
3,5283792095,31MAY2014,20180724.0,20160109.0,20141229.0,20131230.0,20130313.0,20120301.0,70.0,11.0,85.0,9.0,80.0,5.0
4,5031382434,31MAY2014,20170312.0,20160522.0,20121127.0,20120213.0,20091106.0,20080326.0,70.0,85.0,9.0,80.0,5.0,11.0